baseURL: "https://msh1307.kr"
languageCode: en-us
title: msh1307
theme: PaperMod

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 40


params:
  # theme
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "msh1307"
    subtitle: BoB 12th, Sunrin High School 117th, Layer7 22nd 
    imageUrl: "home/macat.jpeg"
    imageWidth: 280
    imageHeight: auto
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "github"
      url: "https://github.com/msh1307"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
